import { Fira_Code } from 'next/font/google'
import './globals.css'
import StyledComponentsRegistry from './styled-components/registry'
import Header from '@/components/Header'

const FiraCode = Fira_Code({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html>
      <body className={FiraCode.className}>
        <StyledComponentsRegistry>
          <div>
            <Header />
          </div>
          {children}
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
